services:
  spring-boot-app:
    image: iraianbu/spring-boot-rest-api:1
    container_name: rest-api
    restart: always
    ports:
      - "8080:8080"
    environment:
        MYSQL_HOST: mysql
        MYSQL_USER: iraianbu
        MYSQL_PASSWORD: iraianbu12!
        MYSQL_PORT: 3306
    depends_on:
      - mysql

  mysql:
    container_name: mysqldb
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: iraianbu
      MYSQL_PASSWORD: iraianbu12!
      MYSQL_DATABASE: dept
    ports:
      - "3308:3306"
